# config/packages/security.yaml

security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            # Retirez "anonymous: true" car il est obsolète et non nécessaire
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email # Specify the name of your email field
                password_parameter: password # Specify the name of your password field
            logout:
                path: app_logout
                target: app_home
            access_denied_url: app_login # Specify the URL to redirect to on access denied

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS } # Utilisez PUBLIC_ACCESS au lieu de IS_AUTHENTICATED_ANONYMOUSLY
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
